---
title: "451 Group Project: Analysis of obesity rates in the United States, by Liuyixin Shao and Yi Su"
output: 
  flexdashboard::flex_dashboard:
     theme:
        version: 4 
        bg: "#ffffff"
        fg: "#000000"
        primary: "#120a8f"
        base_font:
          google: Lato
        code_font:
          google: Lato
     vertical_layout: fill
     orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(shiny)
library(tidyverse)

df <- read_csv('Nutrition__Physical_Activity__and_Obesity_-_Behavioral_Risk_Factor_Surveillance_System.csv')

race_choices <- sort(unique(df$'Race/Ethnicity')) %>% na.omit() 
```

Column {.sidebar data-width=300}
-----------------------------------------------------------------------
#### Control Panel

```{r}
checkboxGroupInput("race", HTML("<b>Races included:</b>"), choices = race_choices, selected = race_choices)

sliderInput("year",
            HTML("<b>Years included:</b>"),
            min = 2011,
            max = 2021,
            value = c(2011, 2021),
            sep = "",
            step = 1
)

HTML("<div style='padding: 10px; background-color: #f0f0f0; margin-top: 10px;'>
        <p><b>Note:</b></p>
        <p>The obesity rate is defined as the proportion of adults with a body mass index (BMI) &ge; 30 kg/m<sup>2</sup></p>
        <p><b>The Abbreviations Comparison Table:</b></p>
        <ul>
          <li>'AS' = 'Asian'</li>
          <li>'OTR' = 'Other'</li>
          <li>'2+' = '2 or more races'</li>
          <li>'NHW' = 'Non-Hispanic White'</li>
          <li>'HPI' = 'Hawaiian/Pacific Islander'</li>
          <li>'AI/AN' = 'American Indian/Alaska Native'</li>
          <li>'HISP' = 'Hispanic'</li>
          <li>'NHB' = 'Non-Hispanic Black'</li>
        </ul>
       </div>")
```

Row {data-width=350}
-----------------------------------------------------------------------

### National Average Obesity Rates by Race
```{r}
data_A <- reactive({
  df_race <- df %>%
  filter(LocationAbbr == 'US') %>%
  filter(Class == 'Obesity / Weight Status') %>%
  filter(Question == 'Percent of adults aged 18 years and older who have obesity') %>%
  filter(`Race/Ethnicity` %in% input$race) %>%
  filter(YearEnd >= input$year[1], YearEnd <= input$year[2]) %>%
  select(`Race/Ethnicity`, Data_Value_Alt) %>%
  na.omit()
  
  df_summary_race <- df_race %>%
  group_by(`Race/Ethnicity`) %>%
  summarise(Avg_Data_Value_Alt = mean(Data_Value_Alt))
  
  average_obesity_rate <- mean(df_race$Data_Value_Alt, na.rm = TRUE) 
  
  df_summary_race %>% arrange(Avg_Data_Value_Alt)

  df_summary_race$`Race/Ethnicity` <- factor(df_summary_race$`Race/Ethnicity`, levels = c("Asian", "Other", "Non-Hispanic White", "2 or more races", "Hispanic", "Hawaiian/Pacific Islander", "American Indian/Alaska Native", "Non-Hispanic Black"))
  
  df_summary_race
  
  list(data = df_summary_race, avg_rate = average_obesity_rate)

})

renderPlot({
  data <- data_A()
  thePlot = ggplot(data$data, aes(x=`Race/Ethnicity`, y=Avg_Data_Value_Alt))  +
    geom_bar(stat="identity", fill = "#404788FF") +
    geom_hline(yintercept = data$avg_rate, linetype = "dashed", color = "red", size = 1) +
    labs(y= "Obesity Rate (%)",
         x = "Race / Ethnicity", 
         title = "National Average Obesity Rates by Race",
         caption = "Source: Centers for Disease Control and Prevention") +
    scale_y_continuous(limits=c(0, 40),
                       breaks=seq(0, 40, 5),
                       labels = c("0%", "5%", "10%", "15%", "20%", "25%", "30%", "35%", "40%")) + 
  scale_x_discrete(
    labels = c(
      "Asian" = "AS",
      "Other" = "OTR", 
      "Non-Hispanic White" = "NHW",
      "2 or more races" = "2+",
      "Hispanic" = "HISP",
      "Hawaiian/Pacific Islander" = "HPI",
      "American Indian/Alaska Native" = "AI/AN",
      "Non-Hispanic Black" = "NHB"
      )) +
    theme_light() + 
    theme(axis.text.x=element_text(size = 15),
          axis.text.y=element_text(size = 15),
          panel.grid.major=element_line(color="Gray", linetype=1),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.x = element_blank(),
          axis.title.y = element_text(size =17),
          axis.title.x = element_text(size =17),
          legend.title = element_text(size =15),
          legend.text = element_text(size =15),
          plot.title = element_text(size = 25, face = 'bold'),
          plot.caption.position = 'plot',
          plot.caption = element_text(size = 13)) +
  geom_text(aes(x = 2, y = data$avg_rate, label = "Average Obesity Rate"), 
            color = "red", 
            size = 3, 
            vjust = -1)

  print(thePlot)
})
```

### Trend of Obesity Rate by Race/Ethnicity
```{r}
data_B <- reactive({
  df_year <- df %>% 
  filter(Class == 'Obesity / Weight Status') %>% 
  filter(LocationAbbr == 'US') %>%
  filter(Question == 'Percent of adults aged 18 years and older who have obesity') %>%
  filter(`Race/Ethnicity` %in% input$race) %>%
  filter(YearEnd >= input$year[1], YearEnd <= input$year[2]) %>%
  select(YearEnd, Data_Value_Alt, `Race/Ethnicity`) %>%
  na.omit
  
  last_values <- df_year %>%
  group_by(`Race/Ethnicity`) %>%
  summarize(last_value = last(Data_Value_Alt)) %>%
  arrange(desc(last_value))

  df_year$`Race/Ethnicity` <- factor(df_year$`Race/Ethnicity`, 
                                   levels = last_values$`Race/Ethnicity`)

  custom_labels <- c(
      "Asian" = "AS",
      "Other" = "OTR", 
      "Non-Hispanic White" = "NHW",
      "2 or more races" = "2+",
      "Hispanic" = "HISP",
      "Hawaiian/Pacific Islander" = "HPI",
      "American Indian/Alaska Native" = "AI/AN",
      "Non-Hispanic Black" = "NHB"
      )
  
  list(data = df_year, custom_labels = custom_labels)

})

renderPlot({
  data <- data_B()
  data <- data_B()
  thePlot <- ggplot(data$data, aes(x = YearEnd, y = Data_Value_Alt, color = `Race/Ethnicity`)) +
  geom_line(size = 1) +
  theme_minimal() +
  labs(title = "Trend of Obesity Rate by Race/Ethnicity",
       x = "Year",
       y = "The Obesity Rate",
       caption = "Source: Centers for Disease Control and Prevention") +
  scale_color_discrete(labels = data$custom_labels) +
  theme(plot.title = element_text(size = 25, hjust = 0.2, face = "bold"),
        axis.text.y = element_text(size =15),
        axis.text.x = element_text(size =15),
        axis.title.y = element_text(size =17),
        axis.title.x = element_text(size =17),
        legend.title = element_text(size =15),
        legend.text = element_text(size =15),
        plot.caption.position = 'plot',
        plot.caption = element_text(size = 13),
        plot.background = element_rect(fill = "white", color = "white")) +
  scale_x_continuous(name = "Year", breaks = seq(2010, 2021, by = 2)) +
  scale_y_continuous(labels = scales::percent_format(scale = 1), limits = c(0, NA))

  print(thePlot)
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Map of Obesity Rate by State

```{r}
filtered_data <- reactive({
  df_filtered <- df %>%
    filter(Class == 'Obesity / Weight Status') %>%
    filter(Question == 'Percent of adults aged 18 years and older who have obesity') %>%
    filter(LocationAbbr != "US") %>%
    filter(`Race/Ethnicity` %in% input$race) %>%
    filter(`YearEnd` >= input$year[1] & `YearEnd` <= input$year[2]) %>%
    select(LocationAbbr, Data_Value_Alt) %>%
    na.omit()
  
  df_summary_filtered <- df_filtered %>%
    group_by(LocationAbbr) %>%
    summarise(Avg_Data_Value_Alt = mean(Data_Value_Alt))
  
  df_summary_filtered <- df_summary_filtered %>%
    rename(state = LocationAbbr)

  df_summary_filtered
})

renderPlotly({
  l <- list(color = toRGB("white"), width = 2)
  g <- list(
    scope = 'usa',
    projection = list(type = 'albers usa'),
    showlakes = TRUE,
    lakecolor = toRGB('white'),
    showland = TRUE,
    landcolor = toRGB("grey70")
  )
  
  min_value <- 10
  max_value <- 45
  
  fig <- plot_geo(filtered_data(), locationmode = 'USA-states') %>%
    add_trace(
      z = ~Avg_Data_Value_Alt, text = ~paste("State: ", state, "<br>Avg Obs Rate: ", scales::percent(Avg_Data_Value_Alt, scale = 1.0, suffix = "%", 
accuracy = 0.01)),
      locations = ~state,
      color = ~Avg_Data_Value_Alt,
      colorscale = "Viridis", 
      colorbar = list(title = "Avg Obs Rate",
                      ticksuffix = "%", 
                      len = 1, 
                      ticklabelposition = "outside right"), 
      zmin = min_value, 
      zmax = max_value,   
      hoverinfo = "text"
    ) %>%
    layout(title = list(text = '<b>Filtered Map of Average Obesity Rate by State</b>', font = list(size = 25, color = "black"), y = 0.99),
           
      geo = g
    ) 
  
  print(fig)
})

```
